language: ruby
rvm:
 - 2.6.7

notifications:
  slack: smarthubwod:TQ3Qh1aOnqeddjujxZJo9vMs

script:
 - echo "Deploying!"
install:
 - npm install -g firebase-tools
after_success:
 - firebase deploy --token $FIREBASE_TOKEN